Sequential Markowitz model
bqth29/simulated-bifurcation-algorithm pull request #19
Opened 2023-09-22 16:53 UTC by bqth29

## PR decription

Following the discussion in #17, the Markowitz API has been enhanced with a new sequential model that allow an optimization of the portfolio relying among others on rebalancing costs which couple the timestamps together:

$$\hbox{argmax } \sum_{t = 1}^{T} w_{t}^{T} \mu_{t} - \frac{\gamma}{2} w_{t}^{T} \Sigma_{t} w_{t} - \Delta w_t^T \Lambda_t \Delta w_t$$

This model is implemented as the `SequentialMarkowitz` class of the `simulated_bifurcation.models` module.

## New features

- The `SequentialMarkowitz` model has been added to the models pool (`simulated_bifurcation.models` module)
- It is now possible to create optimization models without explicitly importing the  `simulated_bifurcation.models` module

```python
import simulated_bifurcation as sb

qubo = sb.models.QUBO()
```

- Minor fixes on the `Markowitz` class
- Unit tests have been added to cover the optimization models

2023-09-26 12:44 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/utils.py
Duplication of `IsingPolynomialInterface.__cast_matrix_to_tensor`

2023-09-26 12:44 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/markowitz.py
> +        self.covariances = cast_to_tensor(covariances)
```suggestion
        self.covariances = self.__cast_to_tensor(covariances, dtype, device)
```

2023-09-26 12:44 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/markowitz.py
> +        self.expected_returns = cast_to_tensor(expected_returns)
```suggestion
        self.expected_returns = self.__cast_to_tensor(expected_returns, dtype, device)
```

2023-09-26 12:44 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/markowitz.py
> +        self.rebalancing_costs = cast_to_tensor(rebalancing_costs)
```suggestion
        self.rebalancing_costs = self.__cast_to_tensor(rebalancing_costs, dtype, device)
```

2023-09-26 12:44 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/markowitz.py
> +from .utils import cast_to_tensor
```suggestion
```

2023-09-29 09:53 UTC, BusyBeaver-42 requested changes

2023-09-29 09:53 UTC, BusyBeaver-42 commented on src/simulated_bifurcation/models/markowitz.py
# Code duplication:
- `portfolio` property defined both in `Markowitz` and `SequentialMarkowitz` with the same code
- `gains` property defined both in `Markowitz` and `SequentialMarkowitz` with the same code
- `gains` emulates the behaviour of the `best_only` argument when calling an optimization method

# Inconsistencies
- `gains` returns `0` when no optimization method has been called which is inconsistent whith the behaviour of the package (should return `None`)

2023-10-01 09:38 UTC, bqth29 commented on src/simulated_bifurcation/models/markowitz.py
The behavior has been optimized by making `Markowitz` inherit from `SequentialMarkowitz`

2023-10-01 13:30 UTC, merged